#ifndef USER_PROTOCOL_COPROC_PROTOCOL_TYPES_H
#define USER_PROTOCOL_COPROC_PROTOCOL_TYPES_H

#include <stddef.h>
#include <stdint.h>

typedef enum
{
    COPROC_STATUS_OK = 0,
    COPROC_STATUS_EMPTY = 1,
    COPROC_STATUS_INVALID_ARG = -1,
    COPROC_STATUS_NO_MEM = -2,
    COPROC_STATUS_INVALID_SIZE = -3,
    COPROC_STATUS_INVALID_CRC = -4,
    COPROC_STATUS_UNSUPPORTED = -5,
    COPROC_STATUS_INVALID_STATE = -6
} CoprocStatus;

#define COPROC_FRAME_MAGIC0 0xA5u
#define COPROC_FRAME_MAGIC1 0x5Au
#define COPROC_FRAME_PROTO_VERSION 0x01u

#define COPROC_FRAME_MAX_PAYLOAD_SIZE 128u
#define COPROC_FRAME_PREFIX_SIZE 12u
#define COPROC_FRAME_CRC_SIZE 2u
#define COPROC_FRAME_MAX_RAW_SIZE (COPROC_FRAME_PREFIX_SIZE + COPROC_FRAME_MAX_PAYLOAD_SIZE + COPROC_FRAME_CRC_SIZE)
#define COPROC_FRAME_MAX_COBS_SIZE (COPROC_FRAME_MAX_RAW_SIZE + (COPROC_FRAME_MAX_RAW_SIZE / 254u) + 1u)
#define COPROC_FRAME_MAX_WIRE_SIZE (COPROC_FRAME_MAX_COBS_SIZE + 1u)

#define COPROC_DEVICE_ROLE_STM32_COPROC 0x01u

#define COPROC_FW_VERSION_MAJOR 0u
#define COPROC_FW_VERSION_MINOR 1u
#define COPROC_FW_VERSION_PATCH 0u
#define COPROC_HW_VERSION 1u
#define COPROC_BOOT_REASON_POWER_ON 0u
#define COPROC_DEFAULT_STREAM_PROFILE_V1 0x01u

typedef enum
{
    COPROC_MSG_CLASS_SYS = 0x01u,
    COPROC_MSG_CLASS_MOTION = 0x02u,
    COPROC_MSG_CLASS_LED = 0x03u,
    COPROC_MSG_CLASS_SENSOR = 0x04u,
    COPROC_MSG_CLASS_POWER = 0x05u
} CoprocMsgClass;

typedef enum
{
    COPROC_FRAME_FLAG_ACK_REQ = 1u << 0,
    COPROC_FRAME_FLAG_RESP = 1u << 1,
    COPROC_FRAME_FLAG_FINAL = 1u << 2
} CoprocFrameFlag;

typedef enum
{
    COPROC_SYS_MSG_HELLO_REQ = 0x01u,
    COPROC_SYS_MSG_HELLO_RSP = 0x02u,
    COPROC_SYS_MSG_ACK = 0x04u,
    COPROC_SYS_MSG_NACK = 0x05u,
    COPROC_SYS_MSG_FAULT = 0x06u
} CoprocSysMsgId;

typedef enum
{
    COPROC_MOTION_MSG_SERVO_MOVE = 0x01u,
    COPROC_MOTION_MSG_SERVO_STOP = 0x02u,
    COPROC_MOTION_MSG_MOTION_DONE = 0x03u,
    COPROC_MOTION_MSG_MOTION_STATE = 0x04u,
    COPROC_MOTION_MSG_SERVO_JOG = 0x05u,
    COPROC_MOTION_MSG_SERVO_SEQUENCE = 0x06u,
    COPROC_MOTION_MSG_SERVO_SEQUENCE_BEGIN = 0x07u,
    COPROC_MOTION_MSG_SERVO_SEQUENCE_CHUNK = 0x08u,
    COPROC_MOTION_MSG_SERVO_SEQUENCE_END = 0x09u,
    COPROC_MOTION_MSG_SERVO_PWM_UNLOCK = 0x0Au,
    COPROC_MOTION_MSG_SERVO_FEEDBACK_RSP = 0x0Bu,
    COPROC_MOTION_MSG_SERVO_PWM_LOCK = 0x0Cu,
    COPROC_MOTION_MSG_SERVO_RELAY_TARGET = 0x0Du,
    COPROC_MOTION_MSG_SERVO_DIRECT_TARGET = 0x0Eu,
    COPROC_MOTION_MSG_SERVO_FEEDBACK_REQ = 0x0Fu
} CoprocMotionMsgId;

typedef enum
{
    COPROC_LED_MSG_SET_RGB = 0x01u,
    COPROC_LED_MSG_BREATHE = 0x02u,
    COPROC_LED_MSG_OFF = 0x03u,
    COPROC_LED_MSG_LED_DONE = 0x04u
} CoprocLedMsgId;

typedef enum
{
    COPROC_SENSOR_MSG_TOUCH_EVENT = 0x01u,
    COPROC_SENSOR_MSG_MAG_STATE = 0x02u,
    COPROC_SENSOR_MSG_IMU_STATE = 0x04u
} CoprocSensorMsgId;

typedef enum
{
    COPROC_POWER_MSG_5V_ENABLE = 0x01u,
    COPROC_POWER_MSG_5V_DISABLE = 0x02u
} CoprocPowerMsgId;

typedef enum
{
    COPROC_MOTION_RESULT_SUCCESS = 0x00u,
    COPROC_MOTION_RESULT_STOPPED = 0x01u,
    COPROC_MOTION_RESULT_INTERRUPTED = 0x02u,
    COPROC_MOTION_RESULT_FAULT = 0x03u
} CoprocMotionResultCode;

typedef enum
{
    COPROC_MOTION_PROFILE_LINEAR = 0x00u,
    COPROC_MOTION_PROFILE_EASE_IN_OUT = 0x01u
} CoprocMotionProfile;

typedef enum
{
    COPROC_LED_RESULT_SUCCESS = 0x00u,
    COPROC_LED_RESULT_FAULT = 0x01u
} CoprocLedResultCode;

typedef enum
{
    COPROC_TOUCH_EVENT_PRESS = 0x01u,
    COPROC_TOUCH_EVENT_RELEASE = 0x02u,
    COPROC_TOUCH_EVENT_LONG_PRESS = 0x03u
} CoprocTouchEventCode;

typedef enum
{
    COPROC_CAPABILITY_MOTION = 1u << 0,
    COPROC_CAPABILITY_LED = 1u << 1,
    COPROC_CAPABILITY_TOUCH = 1u << 2,
    COPROC_CAPABILITY_IMU = 1u << 3,
    COPROC_CAPABILITY_MAGNETOMETER = 1u << 4,
    COPROC_CAPABILITY_RUNTIME_SNAPSHOT = 1u << 5,
    COPROC_CAPABILITY_POWER = 1u << 6
} CoprocCapabilityBit;

typedef enum
{
    COPROC_SENSOR_TOUCH = 1u << 0,
    COPROC_SENSOR_IMU = 1u << 1,
    COPROC_SENSOR_MAGNETOMETER = 1u << 2
} CoprocSensorBit;

typedef enum
{
    COPROC_NACK_REASON_INVALID_PAYLOAD = 0x0001u,
    COPROC_NACK_REASON_UNSUPPORTED_MSG = 0x0002u,
    COPROC_NACK_REASON_UNSUPPORTED_VERSION = 0x0003u,
    COPROC_NACK_REASON_BUSY = 0x0004u,
    COPROC_NACK_REASON_NOT_READY = 0x0005u,
    COPROC_NACK_REASON_INVALID_STATE = 0x0006u,
    COPROC_NACK_REASON_OUT_OF_RANGE = 0x0007u,
    COPROC_NACK_REASON_CAPABILITY_MISSING = 0x0008u,
    COPROC_NACK_REASON_CRC_ERROR = 0x0009u,
    COPROC_NACK_REASON_INTERNAL_ERROR = 0x000Au
} CoprocNackReason;

typedef enum
{
    COPROC_FAULT_SOURCE_MOTION = 0x01u,
    COPROC_FAULT_SOURCE_LED = 0x02u,
    COPROC_FAULT_SOURCE_TOUCH = 0x03u,
    COPROC_FAULT_SOURCE_IMU = 0x04u,
    COPROC_FAULT_SOURCE_MAGNETOMETER = 0x05u,
    COPROC_FAULT_SOURCE_LINK = 0x06u,
    COPROC_FAULT_SOURCE_POWER = 0x07u
} CoprocFaultSource;

#define COPROC_PAYLOAD_LEN_HELLO_REQ 0u
#define COPROC_PAYLOAD_LEN_HELLO_RSP 9u
#define COPROC_PAYLOAD_LEN_ACK 6u
#define COPROC_PAYLOAD_LEN_NACK 8u
#define COPROC_PAYLOAD_LEN_FAULT 9u
#define COPROC_PAYLOAD_LEN_SERVO_MOVE 9u
#define COPROC_PAYLOAD_LEN_SERVO_STOP 2u
#define COPROC_PAYLOAD_LEN_SERVO_JOG 12u
#define COPROC_PAYLOAD_LEN_SERVO_SEQUENCE_BEGIN 4u
#define COPROC_PAYLOAD_LEN_SERVO_SEQUENCE_END 2u
#define COPROC_PAYLOAD_LEN_SERVO_SEQUENCE_CHUNK_HEADER 4u
#define COPROC_PAYLOAD_LEN_SERVO_SEQUENCE_SEGMENT 8u
#define COPROC_PAYLOAD_LEN_SERVO_PWM 2u
#define COPROC_PAYLOAD_LEN_SERVO_RELAY_TARGET 10u
#define COPROC_PAYLOAD_LEN_SERVO_DIRECT_TARGET 6u
#define COPROC_PAYLOAD_LEN_SERVO_FEEDBACK_REQ 0u
#define COPROC_PAYLOAD_LEN_SERVO_FEEDBACK_RSP 13u
#define COPROC_PAYLOAD_LEN_MOTION_DONE 11u
#define COPROC_PAYLOAD_LEN_MOTION_STATE 13u
#define COPROC_PAYLOAD_LEN_LED_SET_RGB 5u
#define COPROC_PAYLOAD_LEN_LED_BREATHE 6u
#define COPROC_PAYLOAD_LEN_LED_OFF 0u
#define COPROC_PAYLOAD_LEN_LED_DONE 5u
#define COPROC_PAYLOAD_LEN_TOUCH_EVENT 6u
#define COPROC_PAYLOAD_LEN_MAG_STATE 6u
#define COPROC_PAYLOAD_LEN_IMU_STATE 11u
#define COPROC_PAYLOAD_LEN_POWER_5V_ENABLE 1u
#define COPROC_PAYLOAD_LEN_POWER_5V_DISABLE 1u

const char *CoprocStatus_ToString(CoprocStatus status);

#endif /* USER_PROTOCOL_COPROC_PROTOCOL_TYPES_H */
