/* Auto-generated by generate_animation_registry.py. Do not edit. */
#include "animation_registry.h"

#include <ctype.h>
#include <stddef.h>

typedef struct {
    const char *name;
    emoji_anim_type_t type;
} animation_registry_name_entry_t;

static const animation_registry_entry_t k_animation_registry[EMOJI_ANIM_COUNT] = {
    [EMOJI_ANIM_BOOT] = {EMOJI_ANIM_BOOT, "boot", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_HAPPY] = {EMOJI_ANIM_HAPPY, "happy", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_ERROR] = {EMOJI_ANIM_ERROR, "error", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_BLUETOOTH] = {EMOJI_ANIM_BLUETOOTH, "bluetooth", true, ANIMATION_ENCODING_RGB565, true},
    [EMOJI_ANIM_SPEAKING] = {EMOJI_ANIM_SPEAKING, "speaking", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_LISTENING] = {EMOJI_ANIM_LISTENING, "listening", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_PROCESSING] = {EMOJI_ANIM_PROCESSING, "processing", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_STANDBY] = {EMOJI_ANIM_STANDBY, "standby", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_THINKING] = {EMOJI_ANIM_THINKING, "thinking", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_CUSTOM_1] = {EMOJI_ANIM_CUSTOM_1, "custom1", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_CUSTOM_2] = {EMOJI_ANIM_CUSTOM_2, "custom2", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_CUSTOM_3] = {EMOJI_ANIM_CUSTOM_3, "custom3", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_STANDBY_1] = {EMOJI_ANIM_STANDBY_1, "standby1", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_STANDBY_2] = {EMOJI_ANIM_STANDBY_2, "standby2", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_STANDBY_3] = {EMOJI_ANIM_STANDBY_3, "standby3", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_STANDBY_4] = {EMOJI_ANIM_STANDBY_4, "standby4", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_DISCONNECT] = {EMOJI_ANIM_DISCONNECT, "disconnect", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_SHOCK] = {EMOJI_ANIM_SHOCK, "shock", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_SUNGLASSES] = {EMOJI_ANIM_SUNGLASSES, "sunglasses", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_SAD] = {EMOJI_ANIM_SAD, "sad", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_GET] = {EMOJI_ANIM_GET, "get", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_SMILE] = {EMOJI_ANIM_SMILE, "smile", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_RECHARGE] = {EMOJI_ANIM_RECHARGE, "recharge", false, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_SPEECHLESS] = {EMOJI_ANIM_SPEECHLESS, "speechless", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_CONCENTRATION] = {EMOJI_ANIM_CONCENTRATION, "concentration", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_FONDLE_LOVE] = {EMOJI_ANIM_FONDLE_LOVE, "fondle_love", false, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_FONDLE_ANGER] = {EMOJI_ANIM_FONDLE_ANGER, "fondle_anger", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_BLINK] = {EMOJI_ANIM_BLINK, "blink", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_UPGRADE] = {EMOJI_ANIM_UPGRADE, "upgrade", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_STANDBY_START] = {EMOJI_ANIM_STANDBY_START, "standby_start", false, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_STANDBY_LOOP] = {EMOJI_ANIM_STANDBY_LOOP, "standby_loop", true, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_STANDBY_END] = {EMOJI_ANIM_STANDBY_END, "standby_end", false, ANIMATION_ENCODING_AUTO, true},
    [EMOJI_ANIM_MUSIC] = {EMOJI_ANIM_MUSIC, "music", true, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_SPEAKING_BLINK] = {EMOJI_ANIM_SPEAKING_BLINK, "speaking_blink", false, ANIMATION_ENCODING_AUTO, false},
    [EMOJI_ANIM_SPEAKING_EYE] = {EMOJI_ANIM_SPEAKING_EYE, "speaking_eye", false, ANIMATION_ENCODING_AUTO, false},
};

static const animation_registry_name_entry_t k_animation_names[] = {
    {"boot", EMOJI_ANIM_BOOT},
    {"happy", EMOJI_ANIM_HAPPY},
    {"success", EMOJI_ANIM_HAPPY},
    {"error", EMOJI_ANIM_ERROR},
    {"bluetooth", EMOJI_ANIM_BLUETOOTH},
    {"speaking", EMOJI_ANIM_SPEAKING},
    {"listening", EMOJI_ANIM_LISTENING},
    {"processing", EMOJI_ANIM_PROCESSING},
    {"analyzing", EMOJI_ANIM_PROCESSING},
    {"standby", EMOJI_ANIM_STANDBY},
    {"idle", EMOJI_ANIM_STANDBY},
    {"normal", EMOJI_ANIM_STANDBY},
    {"thinking", EMOJI_ANIM_THINKING},
    {"custom1", EMOJI_ANIM_CUSTOM_1},
    {"custom2", EMOJI_ANIM_CUSTOM_2},
    {"custom3", EMOJI_ANIM_CUSTOM_3},
    {"standby1", EMOJI_ANIM_STANDBY_1},
    {"standby2", EMOJI_ANIM_STANDBY_2},
    {"standby3", EMOJI_ANIM_STANDBY_3},
    {"standby4", EMOJI_ANIM_STANDBY_4},
    {"disconnect", EMOJI_ANIM_DISCONNECT},
    {"shock", EMOJI_ANIM_SHOCK},
    {"sunglasses", EMOJI_ANIM_SUNGLASSES},
    {"sad", EMOJI_ANIM_SAD},
    {"get", EMOJI_ANIM_GET},
    {"smile", EMOJI_ANIM_SMILE},
    {"recharge", EMOJI_ANIM_RECHARGE},
    {"speechless", EMOJI_ANIM_SPEECHLESS},
    {"concentration", EMOJI_ANIM_CONCENTRATION},
    {"fondle_love", EMOJI_ANIM_FONDLE_LOVE},
    {"fondle-love", EMOJI_ANIM_FONDLE_LOVE},
    {"fondle_anger", EMOJI_ANIM_FONDLE_ANGER},
    {"fondle-anger", EMOJI_ANIM_FONDLE_ANGER},
    {"blink", EMOJI_ANIM_BLINK},
    {"upgrade", EMOJI_ANIM_UPGRADE},
    {"standby_start", EMOJI_ANIM_STANDBY_START},
    {"standby-start", EMOJI_ANIM_STANDBY_START},
    {"standby_loop", EMOJI_ANIM_STANDBY_LOOP},
    {"standby-loop", EMOJI_ANIM_STANDBY_LOOP},
    {"standby_end", EMOJI_ANIM_STANDBY_END},
    {"standby-end", EMOJI_ANIM_STANDBY_END},
    {"music", EMOJI_ANIM_MUSIC},
    {"speaking_blink", EMOJI_ANIM_SPEAKING_BLINK},
    {"speaking-blink", EMOJI_ANIM_SPEAKING_BLINK},
    {"speaking_eye", EMOJI_ANIM_SPEAKING_EYE},
    {"speaking-eye", EMOJI_ANIM_SPEAKING_EYE},
};

static bool names_equal_ignore_case(const char *lhs, const char *rhs) {
    if (lhs == NULL || rhs == NULL) {
        return false;
    }
    while (*lhs != '\0' && *rhs != '\0') {
        if (tolower((unsigned char)*lhs) != tolower((unsigned char)*rhs)) {
            return false;
        }
        ++lhs;
        ++rhs;
    }
    return *lhs == *rhs;
}

const animation_registry_entry_t *animation_registry_get(emoji_anim_type_t type) {
    if (type < 0 || type >= EMOJI_ANIM_COUNT) {
        return NULL;
    }
    return &k_animation_registry[type];
}

const char *animation_registry_name(emoji_anim_type_t type) {
    const animation_registry_entry_t *entry = animation_registry_get(type);
    return entry != NULL ? entry->name : "unknown";
}

bool animation_registry_type_from_name(const char *name, emoji_anim_type_t *out_type) {
    if (name == NULL || out_type == NULL) {
        return false;
    }
    for (size_t index = 0; index < sizeof(k_animation_names) / sizeof(k_animation_names[0]); ++index) {
        if (names_equal_ignore_case(name, k_animation_names[index].name)) {
            *out_type = k_animation_names[index].type;
            return true;
        }
    }
    return false;
}

bool animation_registry_default_loop(emoji_anim_type_t type) {
    const animation_registry_entry_t *entry = animation_registry_get(type);
    return entry != NULL && entry->default_loop;
}

animation_encoding_t animation_registry_encoding(emoji_anim_type_t type) {
    const animation_registry_entry_t *entry = animation_registry_get(type);
    return entry != NULL ? entry->encoding : ANIMATION_ENCODING_AUTO;
}
