#!/usr/bin/env python3
"""Validate the animation registry and generate its C/Python projections."""

from __future__ import annotations

import argparse
import hashlib
import json
import pprint
import re
import sys
from pathlib import Path
from typing import Any


SCRIPT_DIR = Path(__file__).resolve().parent
FIRMWARE_ROOT = SCRIPT_DIR.parent
COMPONENT_ROOT = FIRMWARE_ROOT / "components" / "services" / "anim_service"
DEFAULT_REGISTRY = COMPONENT_ROOT / "animation_registry.json"
DEFAULT_HEADER = COMPONENT_ROOT / "include" / "animation_registry_generated.h"
DEFAULT_SOURCE = COMPONENT_ROOT / "src" / "animation_registry_generated.c"
DEFAULT_PYTHON = SCRIPT_DIR / "animation_registry_generated.py"
NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")
ENUM_RE = re.compile(r"^[A-Z][A-Z0-9_]*$")
SUPPORTED_ENCODINGS = {"auto", "rgb565"}
ANIMATION_FIELDS = {
    "id",
    "name",
    "enum",
    "aliases",
    "source_candidates",
    "legacy_directories",
    "default_loop",
    "encoding",
    "required",
}


def load_registry(path: Path) -> dict[str, Any]:
    data = json.loads(path.read_text(encoding="utf-8"))
    if data.get("schema_version") != 1:
        raise ValueError("animation registry schema_version must be 1")
    if not isinstance(data.get("default_fps"), int) or data["default_fps"] <= 0:
        raise ValueError("animation registry default_fps must be a positive integer")

    animations = data.get("animations")
    if not isinstance(animations, list) or not animations:
        raise ValueError("animation registry animations must be a non-empty list")

    expected_ids = list(range(len(animations)))
    actual_ids = [entry.get("id") for entry in animations]
    if actual_ids != expected_ids:
        raise ValueError(f"animation ids must be contiguous and append-only: expected {expected_ids}, got {actual_ids}")

    known_names: dict[str, str] = {}
    known_enums: set[str] = set()
    for entry in animations:
        unsupported_fields = sorted(set(entry) - ANIMATION_FIELDS)
        if unsupported_fields:
            raise ValueError(f"unsupported fields for animation id {entry.get('id')}: {unsupported_fields}")
        name = entry.get("name")
        enum_name = entry.get("enum")
        aliases = entry.get("aliases")
        candidates = entry.get("source_candidates")
        legacy_dirs = entry.get("legacy_directories")

        if not isinstance(name, str) or not NAME_RE.fullmatch(name) or len(name.encode("utf-8")) >= 24:
            raise ValueError(f"invalid canonical animation name: {name!r}")
        if not isinstance(enum_name, str) or not ENUM_RE.fullmatch(enum_name) or enum_name in known_enums:
            raise ValueError(f"invalid or duplicate animation enum: {enum_name!r}")
        known_enums.add(enum_name)
        if not isinstance(aliases, list) or not all(isinstance(alias, str) and alias for alias in aliases):
            raise ValueError(f"aliases must be non-empty strings for {name}")
        if not isinstance(candidates, list) or not candidates or not all(isinstance(item, str) for item in candidates):
            raise ValueError(f"source_candidates must be a non-empty string list for {name}")
        if not isinstance(legacy_dirs, list) or not all(isinstance(item, str) and item for item in legacy_dirs):
            raise ValueError(f"legacy_directories must be a string list for {name}")
        if entry.get("encoding") not in SUPPORTED_ENCODINGS:
            raise ValueError(f"unsupported encoding for {name}: {entry.get('encoding')!r}")
        if not isinstance(entry.get("default_loop"), bool) or not isinstance(entry.get("required"), bool):
            raise ValueError(f"default_loop and required must be booleans for {name}")

        for candidate in [name, *aliases]:
            normalized = candidate.casefold()
            if normalized in known_names:
                raise ValueError(
                    f"animation name/alias {candidate!r} for {name} conflicts with {known_names[normalized]}"
                )
            known_names[normalized] = name

    return data


def c_bool(value: bool) -> str:
    return "true" if value else "false"


def registry_fingerprint(registry: dict[str, Any]) -> str:
    """Fingerprint the append-only wire contract used by anim_manifest.bin."""
    contract = "".join(f"{entry['id']}:{entry['name']}\n" for entry in registry["animations"])
    return hashlib.sha256(contract.encode("utf-8")).hexdigest()


def render_header(registry: dict[str, Any]) -> str:
    animations = registry["animations"]
    fingerprint = registry_fingerprint(registry)
    anim_enum = "\n".join(f"    EMOJI_ANIM_{entry['enum']} = {entry['id']}," for entry in animations)
    return f"""/* Auto-generated by generate_animation_registry.py. Do not edit. */
#ifndef ANIMATION_REGISTRY_GENERATED_H
#define ANIMATION_REGISTRY_GENERATED_H

#include <stdbool.h>
#include <stdint.h>

typedef enum {{
{anim_enum}
    EMOJI_ANIM_COUNT = {len(animations)},
    EMOJI_ANIM_NONE = -1,
}} emoji_anim_type_t;

typedef enum {{
    ANIMATION_ENCODING_AUTO = 0,
    ANIMATION_ENCODING_RGB565,
}} animation_encoding_t;

typedef struct {{
    emoji_anim_type_t type;
    const char *name;
    bool default_loop;
    animation_encoding_t encoding;
    bool required;
}} animation_registry_entry_t;

#define ANIMATION_REGISTRY_DEFAULT_FPS {registry['default_fps']}
#define ANIMATION_REGISTRY_COUNT {len(animations)}
#define ANIMATION_REGISTRY_FINGERPRINT "{fingerprint}"

#endif /* ANIMATION_REGISTRY_GENERATED_H */
"""


def render_source(registry: dict[str, Any]) -> str:
    animations = registry["animations"]
    entries = []
    aliases = []
    for entry in animations:
        encoding = "ANIMATION_ENCODING_RGB565" if entry["encoding"] == "rgb565" else "ANIMATION_ENCODING_AUTO"
        entries.append(
            f'    [EMOJI_ANIM_{entry["enum"]}] = {{EMOJI_ANIM_{entry["enum"]}, "{entry["name"]}", '
            f'{c_bool(entry["default_loop"])}, '
            f'{encoding}, {c_bool(entry["required"])}}},'
        )
        for name in [entry["name"], *entry["aliases"]]:
            aliases.append(f'    {{"{name}", EMOJI_ANIM_{entry["enum"]}}},')

    return f"""/* Auto-generated by generate_animation_registry.py. Do not edit. */
#include "animation_registry.h"

#include <ctype.h>
#include <stddef.h>

typedef struct {{
    const char *name;
    emoji_anim_type_t type;
}} animation_registry_name_entry_t;

static const animation_registry_entry_t k_animation_registry[EMOJI_ANIM_COUNT] = {{
{chr(10).join(entries)}
}};

static const animation_registry_name_entry_t k_animation_names[] = {{
{chr(10).join(aliases)}
}};

static bool names_equal_ignore_case(const char *lhs, const char *rhs) {{
    if (lhs == NULL || rhs == NULL) {{
        return false;
    }}
    while (*lhs != '\\0' && *rhs != '\\0') {{
        if (tolower((unsigned char)*lhs) != tolower((unsigned char)*rhs)) {{
            return false;
        }}
        ++lhs;
        ++rhs;
    }}
    return *lhs == *rhs;
}}

const animation_registry_entry_t *animation_registry_get(emoji_anim_type_t type) {{
    if (type < 0 || type >= EMOJI_ANIM_COUNT) {{
        return NULL;
    }}
    return &k_animation_registry[type];
}}

const char *animation_registry_name(emoji_anim_type_t type) {{
    const animation_registry_entry_t *entry = animation_registry_get(type);
    return entry != NULL ? entry->name : "unknown";
}}

bool animation_registry_type_from_name(const char *name, emoji_anim_type_t *out_type) {{
    if (name == NULL || out_type == NULL) {{
        return false;
    }}
    for (size_t index = 0; index < sizeof(k_animation_names) / sizeof(k_animation_names[0]); ++index) {{
        if (names_equal_ignore_case(name, k_animation_names[index].name)) {{
            *out_type = k_animation_names[index].type;
            return true;
        }}
    }}
    return false;
}}

bool animation_registry_default_loop(emoji_anim_type_t type) {{
    const animation_registry_entry_t *entry = animation_registry_get(type);
    return entry != NULL && entry->default_loop;
}}

animation_encoding_t animation_registry_encoding(emoji_anim_type_t type) {{
    const animation_registry_entry_t *entry = animation_registry_get(type);
    return entry != NULL ? entry->encoding : ANIMATION_ENCODING_AUTO;
}}
"""


def render_python(registry: dict[str, Any]) -> str:
    animations = registry["animations"]
    fingerprint = registry_fingerprint(registry)
    literal = pprint.pformat(animations, width=120, sort_dicts=False)
    return f'''# Auto-generated by generate_animation_registry.py. Do not edit.

DEFAULT_FPS = {registry["default_fps"]}
REGISTRY_COUNT = {len(animations)}
REGISTRY_FINGERPRINT = "{fingerprint}"
ANIMATIONS = {literal}
ANIMATION_BY_NAME = {{entry["name"]: entry for entry in ANIMATIONS}}
ANIMATION_BY_ALIAS = {{alias: entry for entry in ANIMATIONS for alias in entry["aliases"]}}
'''


def update_or_check(path: Path, expected: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.is_file() else None
    if current == expected:
        return True
    if check:
        print(f"Generated artifact is stale: {path}", file=sys.stderr)
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected, encoding="utf-8", newline="\n")
    print(f"Wrote {path}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--check", action="store_true", help="Fail if any generated artifact is missing or stale")
    args = parser.parse_args()

    try:
        registry = load_registry(args.registry.resolve())
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"Invalid animation registry: {exc}", file=sys.stderr)
        return 2

    outputs = (
        (DEFAULT_HEADER, render_header(registry)),
        (DEFAULT_SOURCE, render_source(registry)),
        (DEFAULT_PYTHON, render_python(registry)),
    )
    return 0 if all(update_or_check(path, content, args.check) for path, content in outputs) else 1


if __name__ == "__main__":
    raise SystemExit(main())
