#ifndef USER_CONFIG_APP_CONFIG_H
#define USER_CONFIG_APP_CONFIG_H

/*
 * 项目级配置常量。
 * 这里集中放应用调度周期、串口缓存和设备地址，避免业务常量散落在 main.c。
 */

#define APP_SERVO_UPDATE_PERIOD_MS 30U
#define APP_SERVO_COMMAND_PULSE_COUNT 0U
#define APP_LED_ENABLE 1U
#define APP_TOUCH_ENABLE 1U
#define APP_QMC6309_ENABLE 0U
#define APP_SENSOR_REPORT_ENABLE 0U
#define APP_SERVO_FEEDBACK_ENABLE 1U
#define APP_SERVO_FEEDBACK_ADC_MAX 4095U
#define APP_SERVO_FEEDBACK_VREF_MV 3300U
#define APP_SERVO_FEEDBACK_AVG_SAMPLES 8U
#define APP_SERVO_FEEDBACK_ADC_TIMEOUT_MS 10U
#define APP_COPROC_SERVO_FEEDBACK_STATE_ENABLE 0U
#define APP_COPROC_SERVO_FEEDBACK_STATE_INTERVAL_MS 50U
#define APP_BOTTOM_IR_ENABLE 1U
#define APP_BOTTOM_IR_ADC_SAMPLE_INDEX 3U
#define APP_BOTTOM_IR_ADC_AVG_SAMPLES 8U
#define APP_BOTTOM_IR_ADC_TIMEOUT_MS 10U
#define APP_BOTTOM_IR_THRESHOLD_RAW 2048U
#define APP_BOTTOM_IR_ACTIVE_ABOVE_THRESHOLD 1U
#define APP_CLI_CMD_BUFFER_SIZE 64U
#define APP_UART_PRINT_BUFFER_SIZE 512U
#define APP_UART_RX_BUFFER_SIZE 64U
#define APP_UART2_RX_BUFFER_SIZE 256U
#define APP_UART2_RX_PREVIEW_BYTES 16U
#define APP_COPROC_STATS_PERIOD_MS 5000U
#define APP_COPROC_OBS_LOG_ENABLE 1U
#define APP_COPROC_SERVO_APPLY_LOG_ENABLE 1U

#define APP_IP5306_KEY_SHORT_PRESS_MS 100U
#define APP_IP5306_KEY_LONG_PRESS_MS 2500U
#define APP_IP5306_KEY_DOUBLE_PRESS_INTERVAL_MS 200U
#define APP_IP5306_KEY_TEST_HOLD_MS 5000U
#define APP_IP5306_BOOT_AUTO_ENABLE 1U
#define APP_IP5306_BOOT_ENABLE_DELAY_MS 20U
#define APP_POWER5V_SERVO_PROBE_ENABLE 1U
#define APP_POWER5V_SERVO_PROBE_DELAY_MS 600U
#define APP_POWER5V_SERVO1_PROBE_ANGLE 70U
#define APP_POWER5V_SERVO2_PROBE_ANGLE 110U

#define APP_I2C_READY_RETRY_COUNT 3U
#define APP_I2C_READY_TIMEOUT_MS 100U
#define APP_I2C_SCAN_TIMEOUT_MS 10U
#define APP_I2C_SENSOR_POWER_STABLE_DELAY_MS 50U
#define APP_BMI160_ENABLE 0U

#define APP_BMI160_ADDR 0x69U
#define APP_BMM150_ADDR 0x11U
#define APP_QMC6309_ADDR 0x7CU

#define APP_BMI160_SCAN_ADDR_0 0x68U
#define APP_BMI160_SCAN_ADDR_1 0x69U
#define APP_BMM150_SCAN_ADDR_0 0x10U
#define APP_BMM150_SCAN_ADDR_1 0x11U
#define APP_QMC6309_SCAN_ADDR 0x7CU

#define APP_WS2812_SIDE_LED_COUNT 16U
#define APP_WS2812_BOTTOM_LED_COUNT 40U
#define APP_WS2812_LED_COUNT                                                                                                \
    ((APP_WS2812_SIDE_LED_COUNT > APP_WS2812_BOTTOM_LED_COUNT) ? APP_WS2812_SIDE_LED_COUNT : APP_WS2812_BOTTOM_LED_COUNT)
#define APP_WS2812_SIDE_DEFAULT_ACTIVE_LED_COUNT 1U
#define APP_WS2812_BOTTOM_DEFAULT_ACTIVE_LED_COUNT APP_WS2812_BOTTOM_LED_COUNT
#define APP_WS2812_RESET_SLOTS 64U
#define APP_WS2812_BIT_0_PULSE 28U
#define APP_WS2812_BIT_1_PULSE 56U
#define APP_WS2812_SHOW_TIMEOUT_MS 10U
#define APP_WS2812_BREATHE_STEP 5U
#define APP_WS2812_BREATHE_INTERVAL_MS 15U
#define APP_WS2812_RAINBOW_STEP 5U
#define APP_WS2812_RAINBOW_INTERVAL_MS 45U
#define APP_WS2812_TEST_STEP_DELAY_MS 250U

#endif /* USER_CONFIG_APP_CONFIG_H */
